import { useEffect, useState } from 'react';

/**
 * Dev-only preview of every transactional email template, rendered with
 * realistic sample data (see quickpost-emails/generate-preview.jsx).
 * Only reachable in local dev — see the DEV-gated route in App.tsx.
 *
 * The static HTML files this reads are generated by:
 *   cd quickpost-emails
 *   npx esbuild generate-preview.jsx --bundle --platform=node --outfile=.preview.cjs --loader:.js=jsx
 *   node .preview.cjs
 * which writes public/email-preview/*.html + manifest.json. Re-run that
 * whenever a template or theme.js changes, then refresh this page.
 */
interface ManifestEntry {
  key: string;
  subject: string;
}

const LABELS: Record<string, string> = {
  emailVerificationOtp: 'Email Verification OTP',
  forgotPassword: 'Forgot Password',
  notificationUpdate: 'Notification Update',
  shipmentMisReport: 'Shipment MIS Report',
  codRemittance: 'COD Remittance',
  weightDiscrepancy: 'Weight Discrepancy',
  ndrShipmentAction: 'NDR Shipment Action',
  orderBooked: 'Order Booked',
  orderShipped: 'Order Shipped',
  outForDelivery: 'Out for Delivery',
  orderDelivered: 'Order Delivered',
};

export function EmailPreview() {
  const [manifest, setManifest] = useState<ManifestEntry[] | null>(null);
  const [active, setActive] = useState<string | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    fetch('/email-preview/manifest.json')
      .then((res) => {
        if (!res.ok) throw new Error('not found');
        return res.json();
      })
      .then((data: ManifestEntry[]) => {
        setManifest(data);
        setActive(data[0]?.key ?? null);
      })
      .catch(() => setError(true));
  }, []);

  if (error) {
    return (
      <div style={{ padding: 40, fontFamily: 'sans-serif', maxWidth: 640 }}>
        <h1 style={{ fontSize: 18, fontWeight: 700 }}>Email preview not generated yet</h1>
        <p style={{ color: '#64748B', fontSize: 14, lineHeight: 1.6 }}>
          Run this once (and again after any template/theme change):
        </p>
        <pre style={{ background: '#F8FAFC', padding: 16, borderRadius: 8, fontSize: 13, overflowX: 'auto' }}>
{`cd quickpost-emails
npx esbuild generate-preview.jsx --bundle --platform=node --outfile=.preview.cjs --loader:.js=jsx
node .preview.cjs`}
        </pre>
        <p style={{ color: '#64748B', fontSize: 14 }}>Then refresh this page.</p>
      </div>
    );
  }

  if (!manifest) {
    return <div style={{ padding: 40, fontFamily: 'sans-serif', color: '#64748B' }}>Loading previews…</div>;
  }

  const activeEntry = manifest.find((m) => m.key === active);

  return (
    <div style={{ display: 'flex', height: '100vh', fontFamily: 'sans-serif' }}>
      {/* Sidebar */}
      <div style={{ width: 260, borderRight: '1px solid #E2E8F0', overflowY: 'auto', flexShrink: 0, background: '#F8FAFC' }}>
        <div style={{ padding: '16px 16px 8px', fontSize: 11, fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: 0.5 }}>
          Email Templates ({manifest.length})
        </div>
        {manifest.map((m) => (
          <button
            key={m.key}
            onClick={() => setActive(m.key)}
            style={{
              display: 'block',
              width: '100%',
              textAlign: 'left',
              padding: '10px 16px',
              border: 'none',
              background: active === m.key ? '#E6F7F1' : 'transparent',
              color: active === m.key ? '#00A86B' : '#334155',
              fontWeight: active === m.key ? 700 : 500,
              fontSize: 13,
              cursor: 'pointer',
            }}
          >
            {LABELS[m.key] || m.key}
          </button>
        ))}
      </div>

      {/* Content */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 }}>
        {activeEntry && (
          <div style={{ padding: '12px 20px', borderBottom: '1px solid #E2E8F0', background: '#fff' }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase' }}>Subject</div>
            <div style={{ fontSize: 14, fontWeight: 600, color: '#0F172A' }}>{activeEntry.subject}</div>
          </div>
        )}
        {active && (
          <iframe
            key={active}
            title={active}
            src={`/email-preview/${active}.html`}
            style={{ flex: 1, border: 'none', width: '100%', background: '#F3F6F4' }}
          />
        )}
      </div>
    </div>
  );
}
